site:
  title: Rancher product documentation
  start_page: main@rancher-product-docs:en:index.adoc

content:
  sources:
    - url: ./ # en
      branches: [main]
    - url: ../fleet-product-docs # en
      branches: [main]
      start_paths: [versions/v0.10, versions/v0.9]
    - url: ../kubewarden-product-docs # en
      branches: [main]
      start_paths: [docs/next, docs/version-*]
    - url: ../longhorn-product-docs # en
      branches: [main]
      start_paths: [docs/version-1.7.0]
    - url: ../rke2-product-docs
      branches: [main]
      start_path: versions/latest # en, zh
    - url: ../k3s-product-docs # en, ja, ko, zh
      branches: [main]
      start_path: versions/latest
    - url: ../turtles-product-docs # en
      branches: [main]
      start_paths: [versions/v0.11, versions/v0.10]
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
    kw-build-type: 'rancher'
    kw-rancher-product-name: 'Rancher Policy Engine'
    kw-community-product-name: 'Kubewarden'
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ja, zh] # ko not supported by extension
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>

output:
  dir: build/site
