site:
  title: Rancher product documentation
  start_page: main@rancher-product-docs:en:index.adoc

content:
  sources:
    - url: https://github.com/rancher/product-docs-playbook.git # en
      branches: [main]
    - url: https://github.com/rancher/fleet-product-docs.git # en
      branches: [main]
      start_paths: [versions/v0.10, versions/v0.9]
    - url: https://github.com/rancher/turtles-product-docs.git # en
      branches: [main]
      start_paths: [versions/v0.11, versions/v0.10]
    - url: https://github.com/rancher/kubewarden-product-docs.git # en
      branches: [main]
      start_paths: [docs/next, docs/version-*]
    - url: https://github.com/rancher/longhorn-product-docs.git # en
      branches: [1.7.0]
    - url: https://github.com/rancher/rke2-product-docs # en, zh
      branches: [main]
      start_path: versions/latest
    - url: https://github.com/rancher/k3s-product-docs # en, ja, ko, zh
      branches: [main]
      start_path: versions/latest
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files
runtime:
  fetch: true
asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
    kw-build-type: 'community'
    kw-rancher-product-name: 'Rancher Policy Engine'
    kw-community-product-name: 'Kubewarden'
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ja, zh] # ko not supported by extension
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>

output:
  dir: build/site
